;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;      ____        __      __              
;;     / __ \____  / /_    __/ /_  ____ ______
;;    / /_/ / __ \/ / / / / __ \/ __ `/ ___/
;;   / ____/ /_/ / / /_/ / /_/ / /_/ / /    
;;  /_/    \____/_/\__, /_.___/\__,_/_/     
;;                /____/                    
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Global WM Settings

[global/wm]
margin-bottom = 0
margin-top = 0

;; File Inclusion
include-file = ~/.config/polybar/colors.ini

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; BASE BAR SETTINGS
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/main]
monitor = ${env:MONITOR:}
monitor-fallback =
monitor-strict = false

bottom = true
fixed-center = true

width = 30%
height = 30
offset-x = 20
offset-y = 20

background = ${color.bg}
foreground = ${color.fg}

radius-top = 12.0
radius-bottom = 12.0

line-size = 0
line-color = #00000000
border-bottom-size = 0
border-color = #00000000

padding = 2
module-margin-left = 1
module-margin-right = 1

font-0 = "Iosevka Nerd Font:size=13;3"
font-1 = "Iosevka Nerd Font:style=Bold:size=18;3"
font-2 = "Iosevka Nerd Font:size=15;3"
font-3 = "Source Code Pro:size=10;3"
font-4 = "Montserrat Medium:style=Medium:size=12;3"
font-5 = "Helvetica Rounded:style=Bold:size=10.5;3"
font-6 = "Hurmit Nerd Font Mono:style=medium:pixelsize=17;3"
font-7 = "Iosevka Nerd Font:size=9;2"
font-8 = "Iosevka Nerd Font:style=Bold:size=12;3"
font-9 = "Hack Nerd Font:style=Regular:size=13;3"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; BARRAS ACTIVAS
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/left]
inherit = bar/main
monitor = ${env:MONITOR:}
override-redirect = true
bottom = false

width = 29%
height = 38
offset-x = 0.5%
offset-y = 5

background = ${color.ahumado}
foreground = ${color.white}

modules-left = my-text-label darkness wireless_status ethernet_status memory_modulo
padding = 0
module-margin-left = 1
module-margin-right = 1

pseudo-transparency = true

[bar/right]
inherit = bar/main
monitor = ${env:MONITOR:}
override-redirect = true
bottom = false

width = 20%
height = 40
offset-x = 80%
offset-y = 5

background = ${color.ahumado}
foreground = ${color.white}

modules-right = bluetooth_module alsa_icon date battery sysmenu
padding = 1
module-margin-left = 1
module-margin-right = 1

pseudo-transparency = true

[bar/tray_isla]
monitor = ${env:MONITOR:}
override-redirect = true

width = 4%
height = 40
offset-x = 68.5%
offset-y = 5
background = ${color.ahumado}
bottom = false
padding = 1
pseudo-transparency = true
modules-center = sep

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; CONFIGURACIÓN GENERAL
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

separator =
spacing = 0
dim-value = 1.0
wm-name = openbox
locale = 

tray-position = none
tray-detached = false
tray-maxsize = 16
tray-transparent = false
tray-background = ${color.bg}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0

wm-restack = bspwm
enable-ipc = true

click-left = 
click-middle = 
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =

cursor-click = 
cursor-scroll = 

;; Application Settings

[settings]
screenchange-reload = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

format-foreground = ${color.white}
format-background = ${color.ahumado}
format-underline =
format-overline =
format-spacing = 0
format-padding = 0
format-margin = 0
format-offset = 0

pseudo-transparency = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;; MÓDULOS DE USUARIO
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/my-text-label]
type = custom/text
# label = "%{T6}%{T-}"
# label = "%{F#8A2BE2}%{F-}"
# label = "%{F#FFFFFF}%{F-}%{K#FFFFFF}%{F#8A2BE2}%{T6} ✖ %{T-}%{F-}%{K-}"
#  abre el semicírculo blanco, %{B#ffffff} rellena el centro de blanco, y  cierra el semicírculo blanco
# label = "%{F#ffffff}%{F-}%{B#ffffff}%{F#8A2BE2}%{T6} ✖ %{T-}%{F-}%{B-}%{F#ffffff}%{F-}"
label = "%{F#8A2BE2}%{T6}  %{T-}%{F-}"
# label-background = #ffffff
# label-background = ${color.bg}
# label-foreground = ${color.deep-purple}
# label-foreground = #8A2BE2
# Agregamos padding al label para que el cuadro blanco envuelva bien la X sin salirse del borde curvo
label-padding = 0
#format-margin = 1

[module/date]
type = internal/date
interval = 1.0
time = %k : %M
date = %b %e
format = <label>
format-foreground = ${color.white}
label = "%{A1:~/.config/polybar/scripts/toggle_cal.sh:}%date%  |  %time% %{A}"
label-font = 6
click-left = gsimplecal &

[module/mpd]
type = internal/mpd
interval = 2
format-online = <label-song>
format-online-foreground = ${color.fg}
label-song = "%title%"
label-song-maxlen = 12
label-song-ellipsis = true
label-offline = "Offline"

;; Apps

[module/term]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.black}
label-background = ${color.bg}
click-left = termite &

[module/web]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.white}
label-background = ${color.bg}
click-left = firefox &

[module/files]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.blue}
label-background = ${color.bg}
click-left = thunar &

[module/edit]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.blue-gray}
label-background = ${color.bg}
click-left = geany &

[module/apps]
type = custom/text
label = "%{T3}%{T-}"
label-foreground = ${color.fg}
label-background = ${color.bg}
click-left = ~/.config/polybar/scripts/launcher &

[module/sep]
type = custom/text
label = " | "
label-font = 1
label-foreground = ${color.fg}

[module/sep2]
type = custom/text
label = "   "
label-foreground = ${color.fg}

[module/alsa_icon]
type = internal/alsa
format-volume-background = ${color.ahumado}
format-muted-background = ${color.ahumado}
format-charging-margin = 0
format-discharging-margin = 0
format-full-margin = 0

format-volume = %{T2}<ramp-volume>%{T-} <label-volume>
format-muted = <label-muted>
label-muted = %{T2}婢%{T-} Muted
label-muted-foreground = ${color.gray}

click-left = amixer -q sset Master toggle
click-right = pavucontrol &

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = #44abff

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 99
poll-interval = 2

format-charging-background = ${color.ahumado}
format-discharging-background = ${color.ahumado}
format-full-background = ${color.ahumado}
format-charging-margin = 0
format-discharging-margin = 0
format-full-margin = 0

format-charging = %{T3}<animation-charging>%{T-} <label-charging>
format-charging-prefix = "%{T2}󱐋 %{T-}"
format-charging-prefix-foreground = ${color.yellow}

format-discharging = %{T2}<ramp-capacity>%{T-} <label-discharging>

format-full = %{T2}<label-full>%{T-}
format-full-prefix = "%{T2} %{T-}"
format-full-prefix-foreground = ${color.light-green}

label-charging = %{T9}%percentage%%%{T-}
label-charging-foreground = ${color.white}
label-discharging = %{T9}%percentage%%%{T-}
label-discharging-foreground = ${color.white}
label-full = %{T9}%percentage%%%{T-}
label-full-foreground = ${color.white}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 
ramp-capacity-foreground = #44abff

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
animation-charging-6 = 
animation-charging-7 = 
animation-charging-8 = 
animation-charging-9 = 
animation-charging-foreground = ${color.green}
animation-charging-framerate = 750

[module/network]
type = internal/network
interface = wlp0s20f3
click-left = kcmshell5 kcm_networkmanagement
interval = 1.0
accumulate-stats = true
unknown-as-up = true

format-connected = <label-connected>
format-connected-foreground = ${color.white}
format-disconnected = <label-disconnected>
format-disconnected-foreground = ${color.gray}

label-connected = 直
label-disconnected = 睊

[module/wireless_status]
type = custom/script
interval = 2
exec = ~/.config/bin/wireless_status.sh

[module/ethernet_status]
type = custom/script
interval = 2
exec = ~/.config/bin/ethernet_status.sh
format = %{T10}<label>%{T-}
format-foreground = ${color.vibrant-orange}
format-padding = 1

[module/memory_modulo]
type = internal/memory
interval = 3
format = <label>
format-background = ${color.ahumado}
format-foreground = ${color.white}
label = "  %{T2}%{T-} %percentage_used%% "
label-font = 1

[module/darkness]
type = custom/script
interval = 2
exec = ~/.config/bin/darkness.sh
format-foreground = ${color.white}

[module/bluetooth_module]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
interval = 10
click-left = bluetoothctl power on
click-right = bluetoothctl power off
click-middle = blueman-manager
format-foreground = ${color.white}
format-background = ${color.ahumado}

[module/sysmenu]
type = custom/text
label = "%{T9}%{T-}"
label-background = ${color.ahumado}
label-foreground = #44abff
click-left = ~/.config/polybar/scripts/powermenu_alt
