[global/wm]
margin-bottom = 0
margin-top = 0

include-file = ~/.config/polybar/colors.ini

[bar/main]
monitor = ${env:MONITOR:}
monitor-fallback =
monitor-strict = false
fixed-center = true
width = 18%
height = 40
offset-x = 20
offset-y = 20
background = ${color.bg}
foreground = ${color.fg}
radius-top = 10.0
radius-bottom = 10.0
line-size = 2
line-color = ${color.ac}
border-size = 0
border-color = ${color.bg}
padding = 2
module-margin-left = 1
module-margin-right = 1
font-0 = "Iosevka Nerd Font:size=21;2"
font-1 = "Iosevka Nerd Font:size=12;2"
font-2 = "Iosevka Nerd Font:bold:size=23;3"
enable-ipc = true

[bar/primary]
inherit = bar/main
monitor = ${env:MONITOR:}
override-redirect = true
wm-restack = bspwm
width = 21%
height = 40
offset-x = 39.5%
offset-y = 5
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = workspaces
fixed-center = true

[module/workspaces]
type = internal/bspwm
pin-workspaces = true
enable-click = true
enable-scroll = true
format-padding = 0

; Mapeo de escritorios por su nombre en BSPWM
icon-1 = 1;
icon-2 = 2;
icon-3 = 3;
icon-4 = 4;
icon-5 = 5;
icon-6 = 6;
icon-7 = 7;
icon-8 = 8;
icon-9 = 9;
icon-10 = 10;

icon-11 = I;
icon-12 = II;
icon-13 = III;
icon-14 = IV;
icon-15 = V;
icon-16 = VI;
icon-17 = VII;
icon-18 = VIII;
icon-19 = IX;
icon-20 = X;

icon-default = 

format = <label-state>
format-background = ${color.bg}

; --- ESTADO ACTIVO / EN FOCO (Verde) ---
label-focused = "%{T3}%{T-} "
label-focused-foreground = #00FF00
label-focused-background = ${color.bg}
label-focused-padding = 0
label-focused-underline = #00FF00

; --- ESTADO OCUPADO (Rojo) ---
label-occupied = "%{T1}%{T-} "
label-occupied-foreground = #FF0000
label-occupied-background = ${color.bg}
label-occupied-padding = 0

; --- ESTADO VACÍO (Blanco) ---
label-empty = "%{T1}%{T-} "
label-empty-foreground = #FFFFFF
label-empty-background = ${color.bg}
label-empty-padding = 0

; --- OCULTAR ESCRITORIOS DE OTROS MONITORES ---
label-dimmed-focused =
label-dimmed-occupied =
label-dimmed-empty =

[settings]
screenchange-reload = false
compositing-background = source
compositing-foreground = over
pseudo-transparency = false

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;     ____     ____     __  __   _      __
;;    / __ \   / _  \   /  |/  / | | /| / /
;;   / /_/ /  / / | /  / /|_/ /  | |/ |/ / 
;;  / _, _/  / /_/ /  / /  / /   |  /|  /  
;; /_/ |_|   \____/  /_/  /_/    |_/ |_/    
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
