[global/wm]
margin-bottom = 0
margin-top = 0

include-file = ~/.config/polybar/colors.ini

[bar/main]
monitor = ${env:MONITOR:}
monitor-fallback =
monitor-strict = false
fixed-center = true
width = 18%
height = 40
offset-x = 20
offset-y = 20
background = ${color.bg}
foreground = ${color.fg}
radius-top = 10.0
radius-bottom = 10.0
line-size = 2
#line-size = 0
line-color = ${color.ac}
# line-color = #00000000
border-size = 0
border-color = ${color.bg}
padding = 2
module-margin-left = 1
module-margin-right = 1
font-0 = "Iosevka Nerd Font:size=21;2"
font-1 = "Iosevka Nerd Font:size=12;2"
font-2 = "Iosevka Nerd Font:bold:size=23;3"
; Habilitamos IPC para que los scripts de apagado funcionen
enable-ipc = true

[bar/primary]
inherit = bar/main
override-redirect = false 
# el original override-redirect = true, pero esto mantiene
# la barra por encima de todo que es algo que no quiero
wm-restack = bspwm
width = 21%
height = 40
offset-x = 39.5%
offset-y = 5
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
modules-center = workspaces
fixed-center = true

[module/workspaces]
type = internal/xworkspaces
pin-workspaces = true
enable-click = true
enable-scroll = true

# Tus iconos intactos
icon-0 = 1;
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-default = 

format = <label-state>
format-background = ${color.bg}

# --- ESTADO ACTIVO ---
# Usamos %icon% para asegurar que use tu icono  que sí existe en la fuente
label-active = "%{T3}%{T-} "
label-active-foreground = #00FF00
label-active-background = ${color.bg}
label-active-padding = 0
# Mantenemos el underline solo para confirmar que sigue ahí
label-active-underline = #00FF00

# --- ESTADO OCUPADO ---
label-occupied = "%icon% "
label-occupied-foreground = ${color.red}
label-occupied-background = ${color.bg}

# --- ESTADO VACÍO ---
label-empty = "%icon% "
label-empty-foreground = ${color.white}
label-empty-background = ${color.bg}

[settings]
screenchange-reload = false
compositing-background = source
compositing-foreground = over
pseudo-transparency = false


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;     ____     ____     __  __   _      __
;;    / __ \   / __ \   /  |/  / | | /| / /
;;   / /_/ /  / / / /  / /|_/ /  | |/ |/ / 
;;  / _, _/  / /_/ /  / /  / /   |  /|  /  
;; /_/ |_|   \___/   /_/  /_/    |_/ |_/    
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
